# Generated by Django 4.2.4 on 2024-04-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimedata',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
