# Generated by Django 4.2.4 on 2024-04-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_realtimedata_humidity_realtimedata_pressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtimedata',
            old_name='humidity',
            new_name='solar_radiation',
        ),
    ]
