# Generated by Django 4.2.4 on 2024-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_humidity_realtimedata_solar_radiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='altitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='realtimedata',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
